version: "3.8"
services:
  my-node-app:
    container_name: express-app-development
    build:
      context: .
      # args:
      #   - NODE_ENV=development
      target: development
    volumes:
      - .:/usr/src/app:ro
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
