version: "3.8"
services:
  my-node-app:
    container_name: express-app-production
    build:
      context: .
      # args:
      #   - NODE_ENV=production
      target: production
    environment:
      - NODE_ENV=production
